spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kory_furniture
    username: postgres
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyenhoainamkory@gmail.com
    password: tgdyurccaeopjgbt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: "*"
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    api-docs:
      path: /v3/api-docs

vnpay:
  tmnCode: U70E11VJ
  hashSecret: 1TEIMA5VO02KZ8AIWPQJMDIEFQXYTFB0
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: http://localhost:3000/pay


jwt:
  signerKey: IGnnbU1ACaOXN6hjMXslkh/B0YTZAnqAk1ezbfvmG9D7L8lklL3DqYBxU7ReFv3s

stripe:
  api:
    secretKey: sk_test_51QF5BKKb2RoKbGIVPeBla2H659Mepf6SGOsTCUvF5bUGNIarMDPOvLvDk9o19fpibRyLTiOKzWkbeymHx5lnt0uC00BDWBwTaK
